# Generated by Django 4.2 on 2023-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='features',
            field=models.CharField(default='000', max_length=255),
        ),
    ]
