# Generated by Django 4.2 on 2023-04-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pass_hash', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeatures',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('features', models.CharField(max_length=400)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pychat.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pychat.profiles')),
            ],
        ),
    ]
